CoED = 'COLLEGE OF EDUCATION (CoED)'
CIVE = 'COLLEGE OF INFORMATICS AND VIRTUAL EDUCATION (CIVE)'
CHAS = 'COLLEGE OF HEALTH AND ALLIED SCIENCES (CHAS)'
SOCIAL = 'COLLEGE OF HUMANITIES AND SOCIAL SCIENCES (CHSS)'
CoES = 'COLLEGE OF EARTH SCIENCES (CoES)'
college_choices = [(CoED, CoED),
                   (CIVE, CIVE),
                   (CHAS, CHAS),
                   (SOCIAL, SOCIAL),
                   (CoES, CoES),
                   ]
